name: Build and Test Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build and start application
      run: mvn spring-boot:run --file pom.xml &

    - name: Wait for application to start
      run: sleep 30s

    - name: Run unittests and integrationtests
      run: mvn test

