name: Dependency Checks Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"  # Jeden Sonntag um 00:00 Uhr UTC ausführen

jobs:
  owasp-dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check

      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: /home/runner/work/joke-application/joke-application/target/dependency-check-report.html